# Generated by Django 5.0.3 on 2024-04-09 14:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('number_of_process', models.CharField(max_length=25, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_number_of_process', message='O número do processo deve estar no formato ^\\d{7}-\\d{2}\\.\\d{4}\\.\\d\\.\\d{2}\\.\\d{4}$', regex='^\\d{7}-\\d{2}\\.\\d{4}\\.\\d\\.\\d{2}\\.\\d{4}$')])),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('type_of_justice', models.CharField(choices=[('JEC', 'Jec'), ('CIVEL COMUM', 'Common Civil'), ('TRABALHISTA', 'Labor'), ('FEDERAL', 'Federal'), ('CRIMINAL', 'Criminal'), ('EXECUÇÃO FISCAL', 'Tax Enforcement'), ('ACPs', 'Acps')])),
                ('receive_by', models.CharField(choices=[('E-MAIL', 'Email'), ('ESAJ', 'Esaj'), ('PJE', 'Pje'), ('PJE-RJ', 'Pje Rj'), ('SALESFORCE', 'Salesforce'), ('RDs', 'Rds'), ('DISTRIBUÍDOS', 'Distributed'), ('OUTROS', 'Others')])),
                ('date_time_of_treaty', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=255)),
                ('hearing_date', models.DateField(blank=True, null=True)),
                ('hearing_time', models.TimeField(blank=True, null=True)),
                ('preliminary_situation', models.CharField(choices=[('DEFERIDO', 'Granted'), ('INDEFERIDO', 'Rejected'), ('NÃO APRECIADA', 'Unappreciated'), ('CITAÇÃO / INTIMAÇÃO', 'Quote'), ('CUMPRIMENTO DE SENTEÇA', 'Enforcement Of Sentence')])),
                ('procedural_stage', models.CharField(choices=[('INGRESSADOS', 'Joined'), ('AVULSO', 'Loose')])),
                ('fatal_deadline', models.DateField(blank=True, null=True)),
                ('obligation_to_do', models.TextField(blank=True, max_length=400, null=True)),
                ('traffic_ticket', models.BooleanField()),
                ('value_of_the_fine', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type_of_fine', models.CharField(blank=True, choices=[('DIÁRIA', 'Daily'), ('ÚNICA', 'Only'), ('POR HORA', 'Hours'), ('POR ATOS', 'By Acts')], max_length=255, null=True)),
                ('judicial_determination', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ceara',
            fields=[
                ('triage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='triage.triage')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_cpf_cnpj', message='O CPF ou CNPJ deve estar no formato correto.', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$|^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')])),
            ],
            bases=('triage.triage',),
        ),
        migrations.CreateModel(
            name='RioDeJaneiro',
            fields=[
                ('triage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='triage.triage')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_cpf_cnpj', message='O CPF ou CNPJ deve estar no formato correto.', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$|^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')])),
            ],
            bases=('triage.triage',),
        ),
        migrations.CreateModel(
            name='SaoPaulo',
            fields=[
                ('triage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='triage.triage')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('stamp_date', models.DateField(blank=True, null=True)),
                ('internal_code', models.IntegerField()),
                ('value_of_the_claim', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            bases=('triage.triage',),
        ),
    ]
