# Generated by Django 5.0.3 on 2024-04-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='fatal_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
