# Generated by Django 5.0.3 on 2024-04-10 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_alter_triage_fatal_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceara',
            name='cpf_cnpj',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_cpf_cnpj', message='O CPF ou CNPJ deve estar no formato correto.', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$|^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='riodejaneiro',
            name='cpf_cnpj',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_cpf_cnpj', message='O CPF ou CNPJ deve estar no formato correto.', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$|^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')]),
        ),
    ]
