# Generated by Django 5.0.3 on 2024-04-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_alter_ceara_cpf_cnpj_alter_riodejaneiro_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
