# Generated by Django 5.0.3 on 2024-04-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0004_alter_triage_arrival_date_alter_triage_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='receive_by',
            field=models.CharField(choices=[('E-MAIL', 'Email'), ('ESAJ', 'Esaj'), ('PJE', 'Pje'), ('PJE-RJ', 'Pje Rj'), ('SALESFORCE', 'Salesforce'), ('RDs', 'Rds'), ('DISTRIBUÍDOS', 'Distributed'), ('ROBÔ', 'Robo'), ('OUTROS', 'Others')]),
        ),
    ]
